---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postee
  name: postee-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/aqua/postee
  persistentVolumeReclaimPolicy: Recycle
