apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: aqua-alm
  name: aquaalm-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/aquaalm/
  persistentVolumeReclaimPolicy: Recycle

