apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: aqua-webhook-pvc
  namespace: aqua
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
